//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab7v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamId { get; set; }
        public int Mark { get; set; }
        public System.DateTime DateExam { get; set; }
        public int StudentId { get; set; }
        public int DcDisciplineId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual DcDiscipline DcDiscipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
