//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab7v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyGroup()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int StudyGroupId { get; set; }
        public string Name { get; set; }
        public int DcSubdivisionId { get; set; }
        public Nullable<System.DateTime> DataVstup { get; set; }
    
        public virtual DcSubdivision DcSubdivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
