//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvclab4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmet
    {
        public int PredmetID { get; set; }
        public int Hours { get; set; }
        public string Name { get; set; }
    }
}
